### ISSUE TITLE
[Task] Sidebar 구현

### ISSUE THREAD

**Issue by suzyhwang** [suzyhwang/pippy#28]
### ISSUE
* Group: client
* Type: feature
* Detail: Sidebar 구현, 로그아웃 모달 연결

### TODO
- [X] Sidebar 틀 구현
- [X] 로그아웃 모달 연결
- [X] Post 모달 연결
- [ ] 반응형 햄버거 만들기

### Estimated time
Pick one
```3h```
