### ISSUE TITLE
[Task] post, comment, userInfo  컴포넌트 구현

### ISSUE THREAD

**Issue by choigicheol** [suzyhwang/pippy#29]
### ISSUE
* Group: client
* Type: feature
* Detail: post, comment, userInfo 컴포넌트 구현

### TODO
- [x] post 컴포넌트 구현
- [x] comment  컴포넌트 구현
- [x] userInfo  컴포넌트 구현

### Estimated time
```3h```
