### ISSUE TITLE
[Task] Profile, Follow 페이지 추가, SideBar(fixed), Thread 댓글입력창 위치 수정

### ISSUE THREAD

**Issue by choigicheol** [suzyhwang/pippy#39]
### ISSUE
* Group: client
* Type: feature
* Detail:Profile, Follow 페이지 추가, SideBar(fixed), Thread 댓글입력창 위치 수정

### TODO
- [x] Profile, Follow 페이지 추가
- [x] Sidebar(fixed) 수정
- [x] Thread 댓글 입력창 위치 수정

### Estimated time
Pick one
```3h```
